name: Go
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go-version:
          - 1.12.x
          - 1.13.x
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - uses: actions/checkout@v1
      - name: Get dependencies
        run: go get ./...

      - name: Test
        run: go test -race -cover  ./...
