name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.12.x
          - 1.13.x
          - 1.14.x
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - uses: actions/checkout@v1
      - name: Get dependencies
        run: go get ./...

      - name: Test
        run: go test -race -cover -coverprofile=coverage.out ./...
